### ISSUE TITLE
ブランチの使い方

### ISSUE THREAD

**Issue by Agatsuma854** [Agatsuma854/get_timetable#2]
masterとfeature-1.3とdevelopで運用しているが使い方をいまいち決めていので, マークダウンもしくはWikiに仕様をまとめたほうが良いと思われる

**Comment by q55mehqs** [comment]
確かに現状のブランチ仕様ではわかりにくいのでfeature-1.3を削除して個人用ブランチ名規則は下のようにします

- q55mehqs/develop <- 個人の作業用ブランチ
- q55mehqs/17 <- 一時作業ブランチ q55mehqs/developにマージさせたら消します (数字はチケット番号)

そして、ある程度メインのdevelopにマージしてもいいかなーって頃合いでプルリク出します
